language: node_js
cache: yarn
node_js:
    - 10

branches:
    only:
        - master
        - /^greenkeeper.*$/

jobs:
    include:
        - stage: test
          script:
              - commitlint-travis
              - yarn lint
              - yarn test --coverage && codecov
          skip_cleanup: true
        - stage: release
          node_js: lts/*
          deploy:
            - provider: script
              skip_cleanup: true
              github_token: $GH_TOKEN
              script: yarn release
          if: branch = master
